### ISSUE TITLE
Blacklist duplicates policy

### ISSUE THREAD

**Issue by marklagendijk** [gulpjs/plugins#124]
What is the policy concerning duplicate plugins in regards to the blacklist? How is determined which of the duplicates doesn't get blacklisted?

The reason I am asking is that I found out that my plugin, [gulp-ng-html2js](https://github.com/marklagendijk/gulp-ng-html2js) was blacklisted. When I searched the issues here, I found issue #117, in which the plugin (and another duplicate) are blacklisted by @miickel, who just happens to be the author of another duplicate.

The readme states:
```
A plugin may be blacklisted for the following reasons:

1. Does not fit within the gulp paradigm
2. Flagrant duplicate of an existing plugin
3. Does not follow the plugin guidelines
```
So when I would follow these rules I would:
1. Block any duplicates which do not follow the guidelines
2. Block all other duplicates, except the first released one.

I don't think that an author of any of the duplicates should be the one who decides which one doesn't get blacklisted. It just feels wrong that in this case this has happened, and the only criteria seemed to be "plugins which do the same as mine, but aren't mine".

**Comment by hivre** [comment]
To chime in on this, how about forks?
e.g. gulp-rev and gulp-rev-all both do revving of files. The latter is a fork of gulp-rev, with a different philosophy and a different feature set.
(although rev-all diverted quite a lot since v.0.8, before that it was more clearly a duplicate)

I wouldn't mind seeing rev-all get removed from the black-list.

**Comment by Dejavs** [comment]
And you are VERY arrogant and Selfish by saying that its your "discretion". Please don't make any open source apps in the future if you ignore our voice. In my opinion "duplicate policy" have destroyed many valuable plugins. I hope it will be better library soon with better and not arogant developers. I'm using now GREAT plugin, which is calles "gulp-uglifyjs" and which have been blacklisted! Its MUCH more better and works properly with streams instead of non blacklisted gulp-uglify. You should allow us to decide which plugin is better than make decission by yourself!

**Comment by contra** [comment]
@hivre The goal is to reduce confusion. If the project is truly it's own thing, why is it ripping off the name of another module?

**Comment by damoncasale** [comment]
It's obvious that bias is involved in the blacklist.  Use it as a reference only, but people will vote with their feet.  Something can be on the blacklist and still be more useful than the non-blacklisted plugin.

I will never, ever use gulp-rev now, after hearing how and why gulp-rev-all got blacklisted.

**Comment by contra** [comment]
@damoncasale If you want something removed from the blacklist open a ticket for discussion, that's how it works. If it doesn't belong on the blacklist it will be removed, it's a community list not a dictatorship - no need to get heated about it.
