### ISSUE TITLE
why the gulp-rev-all is in blacklist?

### ISSUE THREAD

**Issue by jemmyzheng** [gulpjs/plugins#215]
https://github.com/gulpjs/plugins/blob/master/src/blackList.json#L70,
if u check in [gulp-rev-all](https://github.com/smysnk/gulp-rev-all),u can find they are different,may be the rev-all looks did too much things , not simple as gulpJs hope, but i think they are all requlired and useful,
so why  @sindresorhus , the gulp-rev's author. submit the rev-all to the blackList???

**Comment by circlingthesun** [comment]
Gulp-rev only renames files whereas gulp-rev-all renames files as well as replace references to those files in other files. It's a far more complete solution.

**Comment by phated** [comment]
Yeah, looks like it does too many things and those things can be done by gulp-rev in combination with other plugins it lists at https://github.com/sindresorhus/gulp-rev#works-with-gulp-rev

Remember, things should be kept simple and composable.  gulp-rev follows that pattern and has been around forever.

**Comment by circlingthesun** [comment]
@phated It can't actually. If you have a.html that references b.html, and b.html changes that means the reference in a.html will have to change which will affect the hash. Gulp-rev simply hashes your files and leaves the reference replacement to other plugins. This approach is flawed. See https://github.com/smysnk/gulp-rev-all#why-fork

**Comment by phated** [comment]
@circlingthesun please give me the courtesy of doing a tiny semblance of research before you reply.  I already looked at both projects and found it that you can do the same thing with https://github.com/jamesknelson/gulp-rev-replace which is built to work WITH gulp-rev and not try to be some forked replacement.

**Comment by circlingthesun** [comment]
I've use used gulp-rev and gulp-rev-replace before moving to gulp-rev-all. Gulp-rev makes the assumption that you are not revisioning files that reference other revisioned files.

Using gulp-rev with gulp-rev-replace is a fine way to shoot yourself in the foot if this assumption doesn't hold. If you set your cache headers to never expire as suggested in the gulp-rev readme, and then decide to update b.html in my example the following will happen. Your users that visited your site previously and visited a.html (revisioned: a.123.html) will still have it in their cache. When they visit a.html (still: a.123.html) again the hash would not have changed. However b.html has changed and now has a new file name (eg. previously: b.456.html now: b.789.html). Users will get a 404 when clicking a link to b.456.html which no longer exist.

I've experienced this first hand. Not with html files but with lazy loaded js and html templates. It can be really hard to debug. Gulp-rev-all solves with problem for me and others and I think it deserves some visibility.

**Comment by phated** [comment]
@circlingthesun please link the issues you've created on gulp-rev and gulp-rev-replace about those issues.

**Comment by circlingthesun** [comment]
I've not created any issues because the issue cannot be solved when you separate revisioning and reference replacement. I tried my best to explain the problem that gulp-rev-all solves. Maybe @smysnk can do a better job. I understand if you don't have the time to look into it any further. Thanks for your time.

**Comment by smysnk** [comment]
@circlingthesun You explained just fine.

https://github.com/sindresorhus/gulp-rev/issues/46 Here @sindresorhus admits the plugin does not concern itself with dependency graphs.  The alternative solution is multiple passes of revisioning that does not address dependency graphs of linked .html files as described above.

**Comment by phated** [comment]
So what's wrong with the solution proposed after closing?  It seems like using gulp-filter in combination with that suggestion would be fine.

**Comment by smysnk** [comment]
Multiple passes doesn't work with linked html files, since html is revisioned only based on the contents of the html file and not how they reference each other.

eg.
page1.123.html -> hyperlinks -> page2.456.html

After another release page2.456.html release changes to page2.abc.html.

Since page1.123.html did not change, file will remain cached with invalid link to page2.456.html when the new release links to page2.abc.html

**Comment by circlingthesun** [comment]
Multiple passes with gulp-rev won't work. But  ```gulp-rev -> gulp-rev-replace -> gulp-rev -> gulp-rev-replace``` will work for direct references, eg. a.html links to b.html. If a.html indirectly references c.html via this link chain: ```a.html -> b.html -> c.html```, we'll need to run:

```gulp-rev -> gulp-rev-replace -> gulp-rev -> gulp-rev-replace -> gulp-rev -> gulp-rev-replace -> gulp-rev -> gulp-rev-replace```

Otherwise a.html will have a broken link to b.html if c.html changes. The number of times gulp-rev and gulp-rev replace will need to be run is determined by how many levels of indirection there is in your files. I'd recommend running:

```gulp-rev -> gulp-rev-replace -> gulp-rev -> gulp-rev-replace -> gulp-rev -> gulp-rev-replace -> gulp-rev -> gulp-rev-replace -> gulp-rev -> gulp-rev-replace -> gulp-rev -> gulp-rev-replace -> gulp-rev -> gulp-rev-replace -> gulp-rev -> gulp-rev-replace```

just to be safe ;)

**Comment by island205** [comment]
I am a user, both gulp-rev and `gulp-rev-all`. They are totally different.  The reason `"gulp-rev-all": "duplicate of gulp-rev"` in the blacklist is no reasonable. `gulp-rev-all` is do a better work then `gulp-rev` do when i need handle resource dependences.

i use `gulp-rev-all` in more then ten project in my company. it sovles our problem when we use CDN.

being simple and composable does't not mean crude and can't working.

**Comment by phated** [comment]
@island205 Feel free to keep using it; the blacklist is used for the gulp team's sanity and to guide users to the basic solutions. Obviously we have no control over what is published to npm or the internet but we can use best judgement on what new users should be using.  I think the use case for gulp-rev-all is an edge case that people with overly complex systems can and will use but it's not for the majority.

**Comment by circlingthesun** [comment]
We'll just have to agree to disagree. It seems like the blacklist is more likely to reduce your sanity in terms of dealing with issues like this. Btw, you are missing 'gulp-rev-all-fixed' in your list. Perhaps you should rather consider a curated whitelist.

**Comment by phated** [comment]
@circlingthesun thanks, I'll add it

**Comment by island205** [comment]
Ok, you see gulp-rev-all is useful to somebody and different from gulp-rev, So it should not be in the blacklist because is duplicate of gulp-rev, no, it isn't not an copy. You should change the reason for put it in blacklist. Or let it free.

It is not a horrible thing should in blacklist, only is not recommending in recommend list!

A thing in blacklist is considered as ugly  thing by people who did not look deeply. They don't use it. But it is useful.

**Comment by phated** [comment]
@island205 it is a duplicate and even admits it.  It will be staying on the list as far as I am concerned.

**Comment by island205** [comment]
You are the boss

**Comment by PeterRao** [comment]
You are the boss

**Comment by hax** [comment]
@phated I don't think it's an edge case. On the contrary, the fact is `gulp-rev` and `gulp-rev-replace` could only satisfy oversimple cases --- aka, they will never ok for real production usage as my quality standard.

About ten years ago, facebook guys introduce never-expire-cache-by-revision technique for large sites. It require maintaining dependency graphs, (because of possible cycle references, it must be a directed graph, not tree.) If any asset is updated in the new release, the change must be spreaded in the whole dependency graph. That means, rev-and-replace never work from the beginning.

I understand and appreciate the good will of gulp's blacklist, but in this case, put `gulp-rev-all` in it is wrong.

**Comment by island205** [comment]
@hax can't agree more.

**Comment by Huxpro** [comment]
@phated It is obviously not a overly complex case. You want to use [never expire caching](https://developer.yahoo.com/performance/rules.html#expires=), right? So you use `gulp-rev` to sync and 'hash' your filenames with your code changing. However, a simple two-levels dependency break all of your efforts.

I am convinced that you have saw the rise of webpack/rollup.js and the fundamental reason is the power of the ability to take the whole dependency graph in consideration. It's fortunate that @smysnk brings the similar capacity of webpack's [long term caching](https://webpack.github.io/docs/long-term-caching.html) into gulp ecosystem.

Please, don't be a dick to people who contribute to your community.

**Comment by jemmyzheng** [comment]
@Huxpro,thank you for ur support,and this is why i begin to use webpack to work just with the npm script, i agree with u @island205," being simple and composable does't not mean being crude and can't working".^ _ ^

**Comment by littledu** [comment]
`gulp-rev-all + gulp-rev-delete-original` is the best

**Comment by zhangweijie-cn** [comment]
People will vote with their feet

**Comment by smysnk** [comment]
@phated It was a fork a long time ago, but has become a work on its own.  Admitting it was forked does not detract from its uniqueness.  `gulp-rev` has admitted they do not ever plan to cover this use-case so there will before ever a gap in the revision offering by endorsed gulp plugins.  That said, it's no big deal to me.  I find this whole blacklist thing kind of silly which is why I never created this issue on my own.

**Comment by island205** [comment]
That said, It's no big deal to me too. But why i fired this issue from https://github.com/smysnk/gulp-rev-all/issues/140 ?

Because I remomended `gulp-rev-all` in a discussion group on front tech. Someone said `gulp-rev-all` is bad since it is in the blacklist here. I was shocked. The reason I fire this issue is this blacklist affect people， and has missleaded someone on `gulp-rev-all`.

@phated, But you don't care it, am i right?

**Comment by phated** [comment]
Obviously I care or I would have locked this upon close.  I was planning to come in here and suggest some ways we might be able to resolve this but to do that, I had to review the architecture of gulp-rev-all and it is pretty poor.  I don't see a good way to reconcile in it's current state.  Sorry.

**Comment by smysnk** [comment]
Architecture is pretty poor? Please elaborate.

This plugin has gone through a few iterations and in its current form, the flow is pretty easy to follow.  The one thing that should be apparent is there is no likeness to `gulp-rev` left and not a single line of code is shared between the two.

Only possible thing that I could think of to embrace gulps SRP is offload code replacement to something like `gulp-replace`.

**Comment by phated** [comment]
@smysnk When I say architecture, I don't mean the ability to follow the code, but fundamental problems. It is using streams completely wrong and doesn't follow standard node module practices.  Try sending 1000+ large files through and it will crash the process due to buffering every file.

**Comment by circlingthesun** [comment]
There are two phases. First you determine the dependency graph, the after you know this you can compute file hashes and do replacements. If myapp.js is piped through the plugin, you need to the hashes of everything it references before you can compute its hash and pass it downstream. I'm not sure how you would do that without buffering every file.

**Comment by phated** [comment]
@circlingthesun sounds like further thought needs to go into it...

**Comment by circlingthesun** [comment]
@phated, I was hoping that you would enlighten us. I'm genuinely curious as to how the architecture could be improved. I would argue that that 1000+ large files don't all need to be searched for references. In which case you probably don't have to buffer those ones that are only hashed and not searched. Maybe pdf's or large video files. Or did you have something else in mind?

Also what "standard node module practices" are being violated?

**Comment by smysnk** [comment]
Is it not the nature of any revisioning plugin to buffer every file? https://github.com/sindresorhus/gulp-rev/blob/master/index.js#L47

**Comment by circlingthesun** [comment]
@smysnk, I don't think thats the same thing. I think @phated is refering to what happens here https://github.com/smysnk/gulp-rev-all/blob/master/index.js#L20

**Comment by smysnk** [comment]
Ah.  

It could be revised to push binary files through immediately since there are no replacements going on inside of them.

**Comment by island205** [comment]
@circlingthesun Image and font files don't need buffered.

**Comment by contra** [comment]
Further discussion in #219, so I'm closing this.
