### ISSUE TITLE
Don't show modules deprecated on npm

### ISSUE THREAD

**Issue by strugee** [gulpjs/plugins#225]
I'm the author of https://www.npmjs.com/package/stratic-parse-header/. A while ago I marked it as deprecated on npm, but it still shows up in plugins search. This seems unideal.

No rush. Thanks for maintaining gulp <3

**Comment by scniro** [comment]
@strugee  It might be helpful remove the `gulpplugin` keyword seen at [package.json#L29](https://github.com/straticjs/stratic-parse-header/blob/master/package.json#L29) of your project.

> It fetches data from npmsearch with the keywords gulpplugin and gulpfriendly

Might not have to blacklist it since you're the author...

**Comment by contra** [comment]
This should be an easy feature to add, would make a great first PR for anyone to tackle

**Comment by scniro** [comment]
@contra unfortunately I am not sure if this is possible to get the metadata on per 
https://github.com/npm/npm/issues/9861. 

`http://npmsearch.com/query?q=name:gulp-minify-css&fields=deprecated` returns nothing even though [gulp-minify-css](https://www.npmjs.com/package/gulp-minify-css) has long been deprecated...

```
"dependencies": // [...],
"deprecated": "Please use gulp-clean-css",
"description": "Minify css with clean-css.",
"devDependencies": // [...]
```

**Comment by contra** [comment]
@scniro Can't you add ` deprecated:true` to the query to do the same thing?

**Comment by strugee** [comment]
@scniro that's a CLI issue, not an API issue

**Comment by scniro** [comment]
@strugee CLI? I shared a http uri. Stick it in your browser. Try to get a deprecated flag back. If you can, I'll submit a PR for this to work...

**Comment by strugee** [comment]
@scniro npm/npm is a repository for the npm CLI. That issue is about the CLI not displaying this information, not whether it's available.

**Comment by scniro** [comment]
@strugee you've lost me at this point but it seems like you're just arguing about something non-important anyways. If you can get a deprecated flag back - let us know. Otherwise, this issue isn't getting resolved.

**Comment by phated** [comment]
Opened an issue on npmsearch to add the field.

**Comment by strugee** [comment]
@scniro ohhh, I'm sorry!

I assumed this project was querying something under npmjs.com, not npmsearch.com. so I just assumed that npmjs.com would properly return it and npmsearch.com "happening" to not return something was kinda ancillary and irrelevant. My bad; please accept my apologies.

**Comment by scniro** [comment]
@strugee no worries! I actually jumped the gun a bit and I think we could have both been mixing stuff up. I see @phated opened an issue on the npmsearch project which looks like the _actual_ source this is spawned from. I'd imagine the CLI hits those same endpoints internally, and, well, I think we cleared it up 😄 I'm glad to see the issue was opened over there however it doesn't look to be a super active project so hopefully this doesn't drag on too long before we get a response. I already cloned down the plugins project and found where to insert the check for this so if they do indeed expose that property on their API I'll get a PR in for this pretty shortly thereafter. I'll keep my eyes peeled. This will be a nice feature for sure! @phated @contra please free free to assign this my way as I'll be sure to circle back once the folks over at npmsearch hit us back. Thanks all!

**Comment by phated** [comment]
Closing this because the plugin page has been rewritten and integrated with our main website: https://github.com/gulpjs/gulpjs.github.io

I created a new issue on that repository to implement this.
